### PR TITLE
add manual climb

### PR DESCRIPTION
**Pull request by kevinzwang**
I'd like to run this first because the numbers on the auto climb command has ambiguous numbers for tilt and for distance that we can narrow down with this command

### CODE REVIEW

**Comment by doawelul** [comment]
Resolves #72

**Comment by mustangzr1** [comment]
@kevinzwang Please address the merge conflict here.

**Comment by SaltyJoke** [comment]
Resolves #84

**Comment by kevinzwang** [comment]
It would make more sense and be cleaner code to instead negate climber.getEncDistance() instead of all the places where it is called, no?

**Comment by kevinzwang** [comment]
@SaltyJoke WPILib has [a function to reverse encoder values](http://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/Encoder.html#setReverseDirection-boolean-)

**Comment by SaltyJoke** [comment]
1) R.I.P. all logic and common sense 
2) Thanks 
Please make sure I didn't miss anything

**Comment by SaltyJoke** [comment]
Which button do you want for auto climb, which for manual climb?

**Comment by kevinzwang** [comment]
@doawelul fixed drivetrain and merge conflicts. please approve

**Comment by kevinzwang** [comment]
wait before you do that @SaltyJoke do the angle calculations work now?

**Comment by SaltyJoke** [comment]
The angle calculations work now if my geometry is correct.

**Pull request merged**
