### PR TITLE
Issue 78

### LINKED ISSUE #78: Climber cannot tell the difference between ground and platform
The automatic climb stops when the drivetrain is stalled, which happens both at the beginning and at the end of the climb.

### PR DESCRIPTION
**Pull request by SaltyJoke**
Resolves #78 
Do we want to synchronize all the mechanism branches with dev at some point?

### CODE REVIEW

**Comment by SaltyJoke** [comment]
> I thought that we decided on using distance/encoders to measure whether or not we are off the ground (instead of time in this pr). Additionally, I think that it's better to have the override work no matter what.

**Comment by SaltyJoke** [comment]
(Sorry, pressed wrong button.) 
I thought we wanted to use both drivetrain stall and encoders to check if done climbing. The stalled condition needs a timer if we use an 'or' instead of 'and'. I am fine with only using encoders.

**Comment by doawelul** [comment]
We're using encoders to check whether we're off the ground (it doesn't make sense to use it to check whether we have reached the top since we are doing the up-down thing). In other words, I was thinking of using the encoder in place of the timer.

**Comment by SaltyJoke** [comment]
Understood. Made changes ^ 
Anything else?

**Comment by SaltyJoke** [comment]
Thanks. My JDK and/or JAVA_HOME seems to be broken now so I don't have a compiler.

**Pull request merged**
